### ISSUE TITLE
Please host download on Google Drive.

### ISSUE THREAD

**Issue by DouglasB2310** [quiret/magic-txd#2]
MEGA.NZ have bandwidth limit. I can't download without registering an account.
Congrats, nice tool,

**Comment by quiret** [comment]
There are several officially supported download locations for Magic.TXD. Here is a collection, of the hottest:

* http://www.gtainside.com/en/sanandreas/tools/88448-magic-txd-1-0/
* http://www.gtainside.com/en/sanandreas/tools/100160-magic-txd-1-1-winxp/
* http://www.gtagarage.com/mods/show.php?id=27862
* http://www.moddb.com/downloads/magictxd
* http://www.gtagaming.com/downloads/gta-san-andreas/tools/33365
* http://gamebanana.com/tools/5948

I recognize the inconvenience that MEGA.NZ causes. That is why I updated the GTAForums thread main post to post to alternatives. I am not looking forward to hosting on a Google service.

Hoping this solves the issue,
- Martin

**Comment by DouglasB2310** [comment]
Thanks.
